gui:
  showIcons: true
  mouseEvents: false
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
keybinding:
  universal:
    scrollUpMain: "k"
    scrollDownMain: "j"
    prevItem-alt: "<up>"
    nextItem-alt: "<down>"
